language: go
go:
  - 1.5.3
  - 1.6
  - tip
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/aws/aws-sdk-go
script:
  -  go test -cover ./...
